### ISSUE TITLE
Unable to import the solution due to dependencies 

### ISSUE THREAD

**Issue by alex188888** [XRM-OSS/Xrm-Html-Templating#20]
Hello,

We are unable to import the solution due to dependencies the following error occurs when trying toinstall with the latest solution (1.4.2) 
There are missing dependencies. Install the following solutions before installing this solution: "Active"

**Comment by DigitalFlow** [comment]
Hi @alex188888,

This is a weird issue, "Active" is an internal CRM solution which every system contains. There should not even be a reference to that solution from inside the Xrm-Html-Templating solution.
Is this only inside one organization, or can you reproduce this on another one as well?
Did you install Xrm-Templating-Language before? This needs to be imported before importing the Xrm-Html-Templating solution.

Kind Regards,
Florian

**Comment by alex188888** [comment]
So as you expected the issue was related to Xrm-Templating-Language which was not installed before rm-Html-Templating.

 However after creating a simple template it does not appear on the available templates on the email entity, watching the video guide it seems that it was on the old interface

**Comment by DigitalFlow** [comment]
Did you really save your template?
There is no filter logic on the email lookup besides the default filtering for active records.
If your template is not showing, you probably forgot to save.
