### ISSUE TITLE
CRM Dynamics HTML templates - XLT snippets not working

### ISSUE THREAD

**Issue by catalinpotinte** [XRM-OSS/Xrm-Html-Templating#32]
Hello, 

We are encountering the following issue:

1. Edit existing HTML template which contains XLT snippets
2. Switch focus to another content section in the editor
3. Existing Merge tags (snippets )  are removed. Only ${{Snippet is shown in the editor.
4. When using the actual HTML template  the XLT snippet doesnt work anymore.
![image](https://user-images.githubusercontent.com/117435625/201068882-a9a8b4b7-e248-4e6e-86a4-5c0c533d121f.png)

We have the latest solutions installed

1. Xrm.Oss.Xrm-Html-Templating 1.4.3
2. Xrm.Oss.Xrm-Templating-Language 3.9.4

CRM Dynamics Version 1710 (9.2.22101.170) online - 2022 release wave 2.

Any support/hints on how to solve this will be greatly appreciated.

Thank you.

**Comment by DigitalFlow** [comment]
Hi @catalinpotinte,

This is a bug in the upstream unlayer editor. There are already quite a few tickets regarding this issue in their [bug tracker](https://unlayer.canny.io/bug-reports).

I have just published a workaround as prerelease, can you test in your dev environment?
https://github.com/XRM-OSS/Xrm-Html-Templating/releases/tag/v1.4.5

Kind regards,
Florian

**Comment by catalinpotinte** [comment]
Hi @DigitalFlow , 

Thank you for the update.

After installing XrmOssXrmHtmlTemplating_1_4_5_target_CRM_8.0_managed.zip  we noticed that  the existing templates from our system are no longer loaded in the Editor. Select Template doesn't fetch the existing HTML templates 

![image](https://user-images.githubusercontent.com/117435625/203283736-9db2616a-c1c9-4fe7-a0a5-9b093c3d1c2c.png)

Also opening the HTML template/ editing the existing templates in the doesn't help. Changes to the template are not saved.
![image](https://user-images.githubusercontent.com/117435625/203286319-7a431bd2-53b1-4a90-8623-92159e74f121.png)

Installed solutions: XrmOssXrmHtmlTemplating 1.4.5
                              Xrm.Oss.Xrm-Templating-Language 3.9.4

Please let me know if additional details are needed.

Kind regards, 
Catalin

**Comment by catalinpotinte** [comment]
Hi @DigitalFlow 

I was fast yesterday :) and installed v.1.4.6 before you edited the comment to v.1.4.7.
Anyways v1.4.6 solved the Loading/save of existing HTML templates.
I just tried to import v.1.4.7 and the install failed with : Solution manifest import: FAILURE: Holding solution XrmOssXrmHtmlTemplating_Upgrade already exists.

Best Regards, 
Catalin

**Comment by catalinpotinte** [comment]
Hi @DigitalFlow 

Loading/editing/saving templates is available again.

When you first load/edit --> the  snipets are resolved to their name in the editor  e.g. Contact FullName.

If you load the same Template again ->   Contact FullName is displayed as  ${{Snippet("email_contact_fullname")}},

 If i will encounter other issues i will get back to you with details.

Anyways, the Templates work now.

Thank you.

Kind Regards, 
Catalin
